apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: rabbitmq-instances
  namespace: argocd
spec:
  syncPolicy:
    preserveResourcesOnDeletion: false
  generators:
    - list:
        elements:
          - env: main
            url: https://kubernetes.default.svc
            branch: main
  template:
    metadata:
      name: "rabbitmq-{{env}}"
    spec:
      project: rabbitmq
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      source:
        # URL of the repository
        repoURL: git@github.com:gattma/rabbitmq-gitops.git
        # Revision (tag/branch/commit) of the repository (eg HEAD)
        targetRevision: "{{ branch }}"
        # Path within the repository where Kubernetes manifests (and/or Helm, Kustomize, Jsonnet resources) are located
        path: apps/env/{{ env }}
        helm:
          parameters:
          - name: env
            value: "{{ env }}"
      destination:
        server: "{{url}}"
        namespace: "rabbitmq-{{env}}"